config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  scope module: :public do
    root :to =>"homes#top", as: 'top'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'blogs/electric' => 'blogs#electric', as: 'electric'
    get 'blogs/interior' => 'blogs#interior', as: 'interior'
    get 'blogs/tableware' => 'blogs#tableware', as: 'tableware'
    get 'blogs/food' => 'blogs#food', as: 'food'
    delete 'tags/:id' => 'tags#destroy', as: 'tag'
    resources :blogs do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :index]
    get '/search', to: 'searches#search'
  end

  namespace :admin do
    get '/blogs/tag' => 'blogs#tag', as: 'tag'
    resources :users, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :blogs, dependent: :destroy
 has_many :comments, dependent: :destroy

# 退会済みのユーザーが同じアカウントでログイン出来ないよう制約
  def active_for_authentication?
    super && (is_deleted == false)
  end

  #ゲストユーザー
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  # 投稿一覧でユーザーと投稿を紐付ける
  def blogs
    return Blog.where(user_id: self.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :is_deleted)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to top_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class='col-12 mt-4'>
      <h3><%= @user.name %>さんの会員情報変更</h3>
      <div class='bg-warning rounded-pill p-1 mb-3'></div>

      <%= form_with model: @user, url: admin_user_path(@user.id) do |f| %>
        <div class="form-row">
          <%= f.label :ニックネーム, class: 'col-sm-3 col-form-label' %><br />
          <div class="col">
            <%= f.text_field :name, autofocus: true, autocomplete: "inputName" %>
          </div>
        </div>
        <div class="form-row">
          <%= f.label :メールアドレス, class: 'col-sm-3 col-form-label' %><br />
          <div class="col">
          <%= f.email_field :email, autofocus: true, autocomplete: "inputEmail" %>
          </div>
        </div>
        <div class="form-row">
          <%= f.label :会員ステータス, class: 'col-sm-3 col-form-label' %>
          <div class="form-check-inline">
            <%= f.radio_button :is_deleted, false, class: 'form-check-input' %>
            <%= f.label :is_deleted, '有効', value: false, class: 'form-check-label' %>
          </div>
          <div class="form-check-inline">
            <%= f.radio_button :is_deleted, true, class: 'form-check-input' %>
            <%= f.label :is_deleted, '退会', value: true, class: 'form-check-label' %>
          </div>
        </div>
        <div class="mt-4 mb-4">
          <%= f.submit "内容を保存", class: 'btn btn-success' %>
        </div>
      <% end %>

    </div>
  </div>
 </div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class='col-12 mt-4'>
      <h3>会員一覧画面（admin）</h3>
      <div class='bg-warning rounded-pill p-1'></div>
      

      <table class='table table-hover table-inverse'>
        <thead>
            <tr>
              <th>会員ID</th>
              <th>ニックネーム</th>
              <th>メールアドレス</th>
              <th>会員ステータス</th>
              <th colspan="4"></th>
            </tr>
        </thead>
        <% @user.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= user.id %>
            </td>
            <td>
              <%= link_to admin_user_path(user.id) do %>
              <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_deleted == false %>
                <div class="text-success font-weight-bold">有効</div>
              <% else %>
                <div class="font-weight-bold">退会</div>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class='col-12 mt-4'>
      <p id="notice"><%= notice %></p>

      <h3>会員詳細画面（admin）</h3>
      <div class='bg-warning rounded-pill p-1'></div>

      <table class="mt- table table-borderless">
        <tbody>
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
            <tr>
              <td>会員ID</td>
              <td><%= @user.id %></td>
            </tr>
            <tr>
              <td>ニックネーム</td>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <td >会員ステータス</td>
              <td>
                <% if @user.is_deleted == false %>
                  <div class="text-success font-weight-bold">有効</div>
                <% else %>
                  <div class="font-weight-bold">退会</div>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>

        <div class="row mt-2">
          <div class="col-md-3">
            <%= link_to "編集する", edit_admin_user_path(@user.id), class: 'btn btn-success' %>
          </div>
        </div>

      <h3 class='mt-4'>おすすめした商品</h3>
      <div class='bg-warning rounded-pill p-1 mb-3'></div>

      <div class="container">
      <div class="row-container">
      <% @user.blogs.each do |blog| %>
      <div class="blog-box">
       <%= link_to admin_blog_path(blog.id) do %>
         <% if blog.image.attached? %>
           <%= image_tag blog.image, size: "250x250" %>
         <% else %>
           <%= image_tag asset_path('no_image.jpg'), size: "250x250" %>
         <% end %>
      <% end %>
      <p><%= blog.title %></p>
      </div>
      <% end %>
      </div>
      </div>

    </div>
  </div>
</div>