config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  scope module: :public do
    root :to =>"homes#top", as: 'top'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'blogs/electric' => 'blogs#electric', as: 'electric'
    get 'blogs/interior' => 'blogs#interior', as: 'interior'
    get 'blogs/tableware' => 'blogs#tableware', as: 'tableware'
    get 'blogs/food' => 'blogs#food', as: 'food'
    delete 'tags/:id' => 'tags#destroy', as: 'tag'
    resources :blogs do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :index]
    get '/search', to: 'searches#search'
  end

  namespace :admin do
    get '/blogs/tag' => 'blogs#tag', as: 'tag'
    resources :users, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :blog_tags, dependent: :destroy
  has_many :tags, through: :blog_tags

  validates :title,presence:true
  validates :body,presence:true

  #投稿とユーザーidの紐付け
  def user
    return User.find_by(id: self.user_id)
  end

#タグ検索、カラムの中から同じ値がないか探してあればそのまま、なければ新たにカラムに保存します。
  def save_tags(saveblog_tags)
    current_tags = self.tags.pluck(:tagname) unless self.tags.nil?
    old_tags = current_tags - saveblog_tags
    new_tags = saveblog_tags - current_tags

    old_tags.each do |old_tagname|
    self.tags.delete Tag.find_by(tagname: old_tagname)
    end

    new_tags.each do |new_tagname|
    blog_tag = Tag.find_or_create_by(tagname: new_tagname)
    self.tags << blog_tag
    end
  end

end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController

  def index
    @blog = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def tag
    @tag_lists = Tag.all
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to admin_blogs_path, notice: "商品を削除しました。"
  end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/views/admin/blogs/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class='col-12 mt-4'>
      <p id="notice"><%= notice %></p>
      
      <h3>記事一覧画面（admin）</h3>
      <div class='bg-warning rounded-pill p-1'></div>

      <table class='table table-hover table-inverse'>
        <thead>
            <tr>
              <th>会員ID</th>
              <th>画像</th>
              <th>タイトル</th>
              <th>投稿ユーザー</th>
              <th colspan="4"></th>
            </tr>
        </thead>
        <% @blog.each do |blog| %>
        <tbody>
          <tr>
            <td>
              <%= blog.id %>
            </td>
            <td>
              <% if blog.image.attached? %>
              <%= image_tag blog.image, size: "70x70" %>
              <% else %>
              <%= image_tag asset_path('no_image.jpg'), size: "70x70" %>
              <% end %>
            </td>
            <td>
              <%= link_to admin_blog_path(blog.id) do %>
              <%= blog.title %>
              <% end %>
            </td>
            <td>
              <%= link_to admin_user_path(blog.user.id) do %>
              <%= blog.user.name %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>

    </div>
  </div>
</div>

app/views/admin/blogs/show.html.erb
<div class="container">
  <div class="row">
    <div class='ml-1 col mt-4'>
      <h3><%= @blog.title %></h3>
      <div class='bg-warning rounded-pill p-1 mb-3'></div>

      <div class="row mt-5">
        
        <div class="col-4 ml-5">
          <% if @blog.image.attached? %>
          <%= image_tag @blog.image, size: "300x300" %>
          <% else %>
          <%= image_tag asset_path('no_image.jpg'), size: "300x300" %>
          <% end %>
        </div>
        
        <div class="col">
          <div class="row">
            <div class="col-3 font-weight-bold">商品ジャンル</div>
            <div class="col"><%= @blog.genre %></div>
          </div>
          <div class="row mt-3">
            <div class="col-3 font-weight-bold">おすすめしたい人</div>
            <div class="col"><%= @blog.man %></div>
          </div>
          <div class="row mt-3">
            <div class="col-3 font-weight-bold">おすすめ度</div>
            <div class="col">
              <div id="star-rate<%= @blog.id%>"></div>
              <script>
              $('#star-rate<%= @blog.id %>').empty();
              $('#star-rate<%= @blog.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf  : '<%= asset_path('star-half.png') %>',
              half      : false,
              readOnly: true,
              score: <%= @blog.star %>,
              });
              </script>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-3 font-weight-bold">おすすめポイント</div>
            <div class="col"><%= @blog.body %></div>
          </div>
        </div>
      </div>
      
      <div class="col">
        <% @blog.comments.each do |comment| %>
        <div class="list-group-item flex-column align-items-start mt-2">
          <p class="mb-1"><%= comment.comment %></p>
          <div class="text-right">
            <p>
            <%= link_to comment.user.name, admin_user_path(comment.user.id), class: 'text-info font-weight-bold' %>|
            <%= comment.created_at.strftime('%Y/%m/%d') %>|
            <%= link_to '削除', blog_comment_path(@blog.id, comment.id), confirm: 'Are you sure?', method: :delete, class: 'text-dark' %>
            </p>
          </div>
        </div>
        <% end %>
      </div>
      
      <div class="text-center mt-3">
        <%= link_to "商品を削除", admin_blog_path(@blog.id), method: :delete, class: 'btn btn-info' %>
      </div>

    </div>
  </div>
</div>

app/views/admin/blogs/tag.html.erb
<div class="container">
  <div class="row">
    <div class='ml-1 col mt-4'>
      <h3>タグ一覧</h3>
      <div class='bg-warning rounded-pill p-1 mb-3'></div>
      
       <table class='table table-hover table-inverse'>
        <thead>
            <tr>
              <th>タグ</th>
              <th></th>
              <th colspan="2"></th>
            </tr>
        </thead>
        <% @tag_lists.each do |list| %>
        <tbody>
          <tr>
            <td>
              <%= list.tagname %>
            </td>
            <td>
              <%= link_to '削除', tag_path(list.id), confirm: 'Are you sure?', method: :delete %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      





    </div>
  </div>
</div>