config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  scope module: :public do
    root :to =>"homes#top", as: 'top'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'
    get 'blogs/electric' => 'blogs#electric', as: 'electric'
    get 'blogs/interior' => 'blogs#interior', as: 'interior'
    get 'blogs/tableware' => 'blogs#tableware', as: 'tableware'
    get 'blogs/food' => 'blogs#food', as: 'food'
    delete 'tags/:id' => 'tags#destroy', as: 'tag'
    resources :blogs do
      resources :comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :index]
    get '/search', to: 'searches#search'
  end

  namespace :admin do
    get '/blogs/tag' => 'blogs#tag', as: 'tag'
    resources :users, only: [:index, :show, :edit, :update]
    resources :blogs, only: [:index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-12 mt-4'>

      <div class="text-right">
        <% if admin_signed_in? %>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        <% else %>
        <%= link_to "おすすめを教えて！", '/' %>
        <% end %>
      </div>

      <div class="mt-2 text-center">
        <h1 class=>おすすめを教えて！管理者用サイト</h1>
      </div>

      <div class="mt-5 border-top border-bottom">
        <% if admin_signed_in? %>
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <div class="navbar-nav">
              <%= link_to "会員一覧", admin_users_path, class: 'nav-link font-weight-bold' %>
              <%= link_to "記事一覧", admin_blogs_path, class: 'nav-link font-weight-bold' %>
              <%= link_to "タグ一覧", admin_tag_path, class: 'nav-link font-weight-bold' %>
            </duv>
          </div>
        </nav>
        <% else %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class=" mt-5 bg-secondary">
    <p class="text-center text-white">Copyright © Infratop Inc. All Rights Reserved.<p>
  </div>
</footer>

app/views/layouts/_public_header.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-12 mt-4'>

      <div class="text-right">
        <% if user_signed_in? %>
        ようこそ <%= current_user.name %> さん｜<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "新規会員登録", new_user_registration_path %>｜<%= link_to "ログイン", new_user_session_path %> | <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
        <% end %>
      </div>

      <div class="mt-2">
        <%= link_to '/' do%>
        <!--<img src="../../assets/logo.png" class="rounded mx-auto d-block" alt="おすすめを教えてロゴ">-->
        <%= image_pack_tag "logo.png" , class: "rounded mx-auto d-block" %>
       
        <% end %>
      </div>

      <div class="mt-5 border-top border-bottom">
      <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
          <div class="navbar-nav">
            <%= link_to "商品を見る", '/', class: 'nav-link font-weight-bold' %>
            <%= link_to "商品をすすめる", new_blog_path, class: 'nav-link font-weight-bold mx-5' %>
            <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link font-weight-bold' %>
          </duv>
        </div>
      </nav>
      <% else %>
      <% end %>

    </div>

    </div>
  </div>
</div>

app/views/layouts/_sideber.html.erb
<div>
  <div class="font-weight-bold mb-1">ジャンルから探す</div>
    <ul class="list-group list-unstyled">
    <li>  
      <%= link_to "電化製品", electric_path, class: "list-group-item list-group-item-action" %>
    </li>
    <li>
      <%= link_to "インテリア", interior_path, class: "list-group-item list-group-item-action" %>
    </li>
    <li>
      <%= link_to "食器", tableware_path, class: "list-group-item list-group-item-action" %>
    </li>
    <li>
      <%= link_to "食品", food_path, class: "list-group-item list-group-item-action" %>
    </li>
  </ul>
</div>
<!--<strong>検索ワードで探す</strong>-->
<div class="mt-3">
  <div class="font-weight-bold">検索タグで探す</div>
  <% tag_lists.each do |list| %>
  <%= link_to list.tagname, blogs_path(tag_id: list.id), class: 'btn btn-outline-info my-1' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おすすめを教えて！</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
      <% if request.fullpath.include? "admin"  %>
        <%= render 'layouts/admin_header' %>
      <% else%>
         <%= render 'layouts/public_header' %>
      <% end %>
  </header>

  <body>
    <%= yield %>
  </body>
  
  <footer>
     <%= render 'layouts/footer' %>
  </footer>
  
</html>